### PR TITLE
Fixing body order (to reflect table of contents)

### LINKED ISSUE #16: Ensure order in body

### PR DESCRIPTION
**Pull request by alallier**
* Sorted modules in order, so when rendering them in the HTML they have the same order.
* Fixed bug that caused modules with `home` in the name to appear in the `home` part of the JSDocs causing modules to seem out of order

Closes #16

### CODE REVIEW

File: publish.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ var otherApiHtmlData = [];
 function updateOutputFileContent(html, title, filename){
   var trimHtml = html.replace(/(\s|\t)+(\n)+(\s|\t)+/g, '\n').trim();
 
-  if(title.match(/home/i)){
+  if(title.match(/Home/)){
```
Comment (alallier) [inline publish.js]: This still isn't ideal as something like `someModuleNameWhereHomeIsCapitalized` will break this regex
